### ISSUE TITLE
ClassName Error

### ISSUE THREAD

**Issue by dark-wind** [purocean/yii2-template#1]
application/assets/AppAsset.php文件
类名错了
class ApplicationAsset extends AssetBundle
应该是
class AppAsset extends AssetBundle

新来的小朋友怕是跳不出这个坑吧

**Comment by purocean** [comment]
一直走 RESTful 接口所以没测试到，前几天做传统模板发现了这个问题，已修复https://github.com/purocean/yii2-template/commit/0692834a74402d40de0060bcae6f497faa5a3eb1
